package tarantool.com.sp;

import static tarantool.com.sp.SPConstants.addCreatives;

import java.util.List;

import org.tarantool.TarantoolClient;

import tarantool.com.client.TaranToolClientUtil;

public class AddCreatives {
	public static void main(String[] args) {

		TarantoolClient client = TaranToolClientUtil.getClient();
		// CREATIVEID,CAMPAIGNID,CREATIVENAME,CREATIVEURL,TARGETURL,CREATEDDATE,STATUS,MSGSENT,CREATIVEVIEWS,CREATIVECLICKS,CREATIVEGOAL1,CREATIVEGOAL2,TRACKING_CODE,TRACKING_KEY,VERIFIED,TEXTADDESC,CREATIVETYPE,BANNERPATH,CTR,CONVERSION_RATE,COUNTRY_PHONE_CODE,DESTINATION_NUMBER,MSG_BODY_TEXT,TEXTADTITLE,ADIMAGE,REASON_DISAPPROVED,APPROVED_DATETIME,VERIFIEDBY,CLICKURL,SKIPBUTTONCOLOR,MOREBUTTONCOLOR,SKIPBUTTONTEXT,MOREBUTTONTEXT,IMAGESIZE,APPROVED_DTRS,ECPM,TEXTCOLOR,TEXTBGCOLOR,IS_IMAGE_SYNCED,SIZE_CATEGORY,TAG_TYPE,OPTIMIZER_ENABLED
		List<?> result = client.syncOps().call(addCreatives, 11111,2118232,1003,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42);
		System.out.println("addCreatives Result- " + result.toString());

	}
}
